# Build the Vite SPA, then serve static files on Cloud Run's $PORT.
FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm ci

COPY . .

# Vite inlines these at build time. Pass via --build-arg / Cloud Build substitutions.
ARG VITE_APP_BACKEND_URL
ARG VITE_APP_FRONTEND_URL
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_AUTH_MODE
ARG VITE_QUICKBOOKS_PAYMENTS_TOKEN_ENDPOINT
ARG VITE_QUICKBOOKS_PAYMENTS_SAVE_ENDPOINT
ARG VITE_PAYMENT_AUTHORIZATION_FORM_URL
ARG VITE_CLIENT_PORTAL_SERVICE_OUTCOMES_URL

ENV VITE_APP_BACKEND_URL=$VITE_APP_BACKEND_URL \
    VITE_APP_FRONTEND_URL=$VITE_APP_FRONTEND_URL \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_AUTH_MODE=$VITE_AUTH_MODE \
    VITE_QUICKBOOKS_PAYMENTS_TOKEN_ENDPOINT=$VITE_QUICKBOOKS_PAYMENTS_TOKEN_ENDPOINT \
    VITE_QUICKBOOKS_PAYMENTS_SAVE_ENDPOINT=$VITE_QUICKBOOKS_PAYMENTS_SAVE_ENDPOINT \
    VITE_PAYMENT_AUTHORIZATION_FORM_URL=$VITE_PAYMENT_AUTHORIZATION_FORM_URL \
    VITE_CLIENT_PORTAL_SERVICE_OUTCOMES_URL=$VITE_CLIENT_PORTAL_SERVICE_OUTCOMES_URL

RUN npm run build

FROM node:20-bookworm-slim AS runtime

WORKDIR /app

ENV NODE_ENV=production \
    PORT=8080

RUN npm install --global serve@14.2.6 \
  && useradd --system --uid 1001 --create-home appuser

COPY --from=build /app/dist ./dist

USER appuser

EXPOSE 8080

CMD ["sh", "-c", "serve -s dist -l tcp://0.0.0.0:${PORT}"]
